---
deployment:
  tasks:
    - source "$HOME/nodevenv/repositories/msmtnepal/22/bin/activate" && cd "$HOME/repositories/msmtnepal" && npm ci && NODE_OPTIONS=--max-old-space-size=1536 npm run build && mkdir -p tmp && touch tmp/restart.txt
