import type { Metadata } from 'next'
import { PageIntro } from '@/components/SiteChrome'
import { getPublicTeam, type PublicTeamMember } from '@/lib/content'

export const dynamic = 'force-dynamic'

export const metadata: Metadata = { title: 'Our Team', description: 'Meet the people behind Medical Services Management Trust Nepal.', alternates: { canonical: '/our-team' }, openGraph: { title: 'Our Team | MSMT Nepal', description: 'Meet the people behind Medical Services Management Trust Nepal.', url: '/our-team', type: 'website' } }
type TeamProfile = PublicTeamMember & { portrait?: string }
const profiles: TeamProfile[] = [
{name:'Kumar Jung Thakuri',roleTitle:'Chairperson, Executive Committee',portrait:'/images/team/Kumar.png',biography:'A finance and management professional with over four decades of experience in financial management, human resources and governance. He holds a master’s degree in business studies and is an ACCA Scholar, with expertise in strategic planning, institutional development and resource mobilization. He provides strategic leadership and governance oversight to MSMT Nepal.'},
{name:'Bina Maharjan',roleTitle:'Vice Chairperson, Executive Committee',portrait:'/images/team/Bina.png',biography:'A founding member of MSMT Nepal and advocate for gender equality, with 25 years of experience at United Mission to Nepal as an Administrative Officer and Gender Trainer. She is also founder and chairperson of Sambhawana Nepal, promoting women’s empowerment, and an active GBV advocate.'},
{name:'Bikash Pandey',roleTitle:'Secretary, Executive Committee',portrait:'/images/team/Bikash.jpg',biography:'A microbiology professional with a master’s degree, leadership experience in biotechnology and quality management, and certification in ISO and quality assurance auditing. His work focuses on quality medicines, diagnostics, pharmacovigilance and patient-centered healthcare.'},
{name:'Kalyan Bikram Shah',roleTitle:'Treasurer, Executive Committee',portrait:'/images/team/Kalyan.jpg',biography:'A finance, administration and grants management professional with more than 18 years of experience, including over 15 years in the development sector. He supports financial oversight, accountability, internal controls and sound governance at MSMT Nepal.'},
{name:'Bhim Prasad Pokhrel',roleTitle:'Member, Executive Committee',portrait:'/images/team/Bhim.jpg',biography:'Founder chairperson and part-time lead of MSMT Nepal, with over three decades of development-sector experience. He contributes to organizational management, governance, strategic planning and stakeholder relationships.'},
{name:'Yagya Prasad Chapagai',roleTitle:'Board Member',portrait:'/images/team/Yagya.jpg',biography:'A financial professional with over four decades of experience across national and international NGOs and the private sector. A former Finance and Administration Director and Vice President of MSMT Nepal, he brings deep institutional knowledge and governance experience.'},
{name:'Shyam Narayan Shrestha',roleTitle:'Legal Advisor',portrait:'/images/team/Shyam.jpg',biography:'A Senior Advocate with over 30 years of legal practice. He holds degrees in sociology and law from Tribhuvan University and has served as Chief Attorney of Bagmati Province, advising organizations and representing clients across Nepal’s judiciary.'},
{name:'Bade Babu Thapa',roleTitle:'Pharmaceutical Advisor',portrait:'/images/team/Bade.png',biography:'A senior pharmacist and technical advisor with over 42 years of service in community health, immunization and pharmaceutical supply chain management in Nepal. His expertise includes vaccine lifecycle management, essential medicines, cold chain, regulatory compliance and quality assurance.'},
{name:'Puran Malla Thakuri',roleTitle:'Operations Manager',portrait:'/images/team/Puran.png',biography:'Brings over two decades of experience managing medicines and surgical supplies. His expertise includes inventory control, procurement, supply chain management and coordination with health organizations, suppliers and customers.'},
{name:'Jhabendra Prakash Bhattarai',roleTitle:'Administration and Finance Manager',portrait:'/images/team/Jhabendra.jpg',biography:'Holds a master’s degree in management from Tribhuvan University and has over 20 years of experience in finance and programme management. Since joining MSMT Nepal in 2024, he has helped strengthen financial systems, compliance and organizational capacity.'},
{name:'Bhumika Shrestha',roleTitle:'Pharmacy Officer',portrait:'/images/team/Bhumika.png',biography:'A qualified pharmacy professional with a Bachelor of Pharmacy and Diploma in Pharmacy, and over 10 years of hospital pharmacy experience. Her work includes medication management, dispensing, inventory control, quality assurance and promoting safe, rational medicine use.'},
]
export default async function TeamPage(){const cmsPeople=await getPublicTeam();const people:TeamProfile[]=cmsPeople.length?cmsPeople.map(person=>({...person,portrait:person.portraitUrl||profiles.find(profile=>profile.name===person.name)?.portrait})):profiles;return <><PageIntro eyebrow="Our Team" title="People behind the work" description="Meet the Executive Committee and senior staff bringing experience in healthcare, finance, governance, quality and community service."/><section className="content-section"><div className="container"><div className="team-grid">{people.map(person=><article className="team-card" key={person.name}>{person.portrait&&<img className="team-portrait" src={person.portrait} alt={person.portraitAlt||`Portrait of ${person.name}`} loading="lazy"/>}<div className="team-details"><p className="eyebrow">{person.roleTitle}</p><h2>{person.name}</h2>{person.biography&&<p>{person.biography}</p>}</div></article>)}</div></div></section></>}
