import Link from 'next/link'
import { SectionHeading } from '@/components/SiteChrome'
import { services, site } from '@/lib/site'
import { getPublicMedia, getPublicServices } from '@/lib/content'

export const dynamic = 'force-dynamic'

export const metadata = { title: 'Home', description: 'MSMT Nepal works to improve access to essential medicines and healthcare services through dependable supply and community-focused services.', alternates: { canonical: '/' }, openGraph: { title: 'Medical Services Management Trust Nepal (MSMT Nepal)', description: 'MSMT Nepal works to improve access to essential medicines and healthcare services through dependable supply and community-focused services.', url: '/', type: 'website' as const } }

export default async function HomePage() {
  const [publicServices, publicMedia] = await Promise.all([getPublicServices(), getPublicMedia()])
  return <>
    <section className="hero"><div className="container hero-grid"><div><p className="eyebrow">Healthcare access across Nepal</p><h1>Essential medicine.<br/>Closer to everyone.</h1><p className="hero-copy">MSMT Nepal works to strengthen access to essential medicines and healthcare support through dependable supply and community-focused services.</p><div className="actions"><Link className="button button-primary" href="/services">Explore services <span aria-hidden="true">→</span></Link><Link className="button button-secondary" href="/about">Learn about MSMT</Link></div></div><div className="hero-photo" role="img" aria-label="MSMT Nepal clinic and community space"><span className="art-label">Community-focused care</span></div></div></section>
    <section className="metric-band" aria-label="About MSMT Nepal"><div className="container"><div className="metric-grid"><div className="metric"><strong>2004</strong><span>Established in Nepal</span></div><div className="metric"><strong>People</strong><span>At the center of our work</span></div><div className="metric"><strong>Access</strong><span>Essential medicines and care</span></div></div></div></section>
    <section className="section section-wash"><div className="container"><SectionHeading eyebrow="What we do" title="Services that support healthier communities" copy="Reliable medicine supply and practical care, designed around community needs."/><div className="service-grid">{publicServices.slice(0,3).map(service=><article className="service-card" key={service.slug||service.title}><span className="service-icon" aria-hidden="true">{services.find(item=>item.title.toLowerCase()===service.title.toLowerCase())?.icon||'✚'}</span><span className={`status ${service.status==='planned'?'status-planned':service.status!=='current'?'status-confirm':''}`}>{service.status==='current'?'Current service':service.status==='planned'?'Planned':'Status to confirm'}</span><h3>{service.title}</h3><p>{service.summary}</p></article>)}</div><div className="center-action"><Link className="button button-secondary" href="/services">View all services</Link></div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="Our purpose" title="Better access, stronger health systems" copy="MSMT Nepal is a professional, socially driven trust established in 2004 to help make quality medicines and healthcare more accessible, especially for poor and vulnerable communities."/><div className="purpose-grid"><article className="info-card"><p className="eyebrow">Objectives</p><h3>Reliable and affordable care</h3><p>Ensure continuous access to essential medicines and medical equipment, strengthen sustainable supply systems, build healthcare capacity, and reinvest surpluses in service improvement.</p></article><article className="info-card"><p className="eyebrow">Services</p><h3>Support from supply to community care</h3><p>Medicine and medical goods supply, doorstep medicine delivery, community clinic care, annual health camps, humanitarian response, and professional training for healthcare providers.</p><Link className="text-link" href="/services">Explore MSMT services →</Link></article></div></div></section>
    <section className="section"><div className="container approach-grid"><div className="approach-art" role="img" aria-label="Abstract illustration of a healthcare document"/><div className="content-copy"><p className="eyebrow">Our approach</p><h2>Quality and reliability</h2><p>MSMT Nepal brings together medical, pharmaceutical and management professionals to support dependable medicine supply and stronger healthcare services.</p><ul className="check-list"><li>Working with health providers and communities</li><li>Supporting sustainable medicine supply</li><li>Building skills through training and collaboration</li></ul><Link className="text-link" href="/about">Learn about our approach →</Link></div></div></section>
    <section className="section section-wash"><div className="container"><div className="section-title-row"><SectionHeading eyebrow="From MSMT" title="Stories, updates and resources"/><Link className="text-link" href="/media">Visit Media →</Link></div>{publicMedia.length ? <div className="media-grid">{publicMedia.slice(0,3).map(item=><article className="media-card" key={item.slug}><div className="media-visual" aria-hidden="true">{item.category==='report'?'▤':'✳'}</div><p className="media-kicker">{item.category}</p><h3><Link href={`/media/${item.slug}`}>{item.title}</Link></h3><p>{item.summary}</p></article>)}</div> : <div className="media-empty"><h3>Updates and resources</h3><p>Contact MSMT Nepal to learn more about its services and work with communities.</p></div>}</div></section>
    <section className="cta-band"><div className="container cta-inner"><div><h2>Let’s connect</h2><p>For service inquiries and partnerships, contact MSMT Nepal.</p></div><Link href="/contact" className="button button-light">Contact MSMT →</Link></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Organization','name':site.name,'url':site.url,'email':site.email,'telephone':site.phones,'address':{'@type':'PostalAddress','streetAddress':site.address,'addressCountry':'NP'}})}}/>
  </>
}
